# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeat_times', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewords.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=100)),
                ('time', models.DateTimeField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewords.User')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
                ('example', models.TextField(max_length=100)),
                ('synonym', models.CharField(max_length=100)),
                ('is_cet4', models.BooleanField(default=False)),
                ('is_cet6', models.BooleanField(default=False)),
                ('is_toefl', models.BooleanField(default=False)),
                ('is_ielts', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewords.Words'),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewords.Words'),
        ),
    ]
