# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0002_auto_20160830_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglist',
            name='last_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='words',
            name='english',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='words',
            name='example',
            field=models.TextField(max_length=1000),
        ),
    ]
