# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0004_auto_20160831_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglist',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
