# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0007_auto_20160901_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninglist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='learninglist',
            name='target_word',
        ),
        migrations.DeleteModel(
            name='LearningList',
        ),
    ]
