# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewords', '0008_auto_20160905_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeat_times', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewords.Words')),
            ],
        ),
    ]
