# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0010_auto_20160907_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learninglist',
            old_name='target_word',
            new_name='word',
        ),
    ]
