# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewords', '0011_auto_20160907_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learninglist',
            old_name='last_time',
            new_name='review_time',
        ),
    ]
